using System;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using MegaCrit.Sts2.Core.Helpers;

namespace BetaDirectConnect;

public sealed class BetaDirectConnectRuntimeConfig
{
    [JsonPropertyName("host_port")]
    public int HostPort { get; set; } = 33771;

    [JsonPropertyName("join_ip")]
    public string JoinIp { get; set; } = "127.0.0.1";

    [JsonPropertyName("join_port")]
    public int JoinPort { get; set; } = 33771;

    [JsonPropertyName("player_id")]
    public ulong PlayerId { get; set; } = 1000;

    [JsonPropertyName("player_id_text")]
    public string PlayerIdText { get; set; } = "";
}

public static class BetaDirectConnectConfigService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = null,
    };

    public static BetaDirectConnectRuntimeConfig Current { get; private set; } = new();

    public static ulong EffectivePlayerId => GetCommandLinePlayerId() ?? Current.PlayerId;

    public static string EffectivePlayerIdText => string.IsNullOrWhiteSpace(Current.PlayerIdText)
        ? EffectivePlayerId.ToString()
        : Current.PlayerIdText;

    public static string ConfigPath => Path.Combine(GetModDirectory(), "BetaDirectConnect.runtime.config");

    public static void Initialize()
    {
        Reload();
        EnsureAutoGeneratedPlayerId();
        MainFile.Logger.Info($"BetaDirectConnect effective player ID: {EffectivePlayerId}");
    }

    public static void Reload()
    {
        try
        {
            if (!File.Exists(ConfigPath))
            {
                Current = new BetaDirectConnectRuntimeConfig();
                Save();
                return;
            }

            string json = File.ReadAllText(ConfigPath);
            Current = JsonSerializer.Deserialize<BetaDirectConnectRuntimeConfig>(json, JsonOptions) ?? new BetaDirectConnectRuntimeConfig();
            NormalizeInPlace(Current);
        }
        catch (Exception ex)
        {
            Current = new BetaDirectConnectRuntimeConfig();
            MainFile.Logger.Error($"Failed to load BetaDirectConnect config: {ex}");
        }
    }

    public static void Save()
    {
        NormalizeInPlace(Current);
        Directory.CreateDirectory(GetModDirectory());
        File.WriteAllText(ConfigPath, JsonSerializer.Serialize(Current, JsonOptions));
    }

    public static void UpdateHostPort(int port)
    {
        Current.HostPort = NormalizePort(port);
        Save();
    }

    public static void UpdateJoinSettings(string ip, int port, string playerIdText, ulong playerId)
    {
        Current.JoinIp = string.IsNullOrWhiteSpace(ip) ? "127.0.0.1" : ip.Trim();
        Current.JoinPort = NormalizePort(port);
        Current.PlayerIdText = string.IsNullOrWhiteSpace(playerIdText) ? playerId.ToString() : playerIdText.Trim();
        if (!GetCommandLinePlayerId().HasValue)
        {
            Current.PlayerId = NormalizePlayerId(playerId);
        }
        Save();
    }

    public static int NormalizePort(int port)
    {
        return Math.Clamp(port, 1, 65535);
    }

    public static ulong NormalizePlayerId(ulong playerId)
    {
        return playerId <= 1 ? 0UL : playerId;
    }

    private static void NormalizeInPlace(BetaDirectConnectRuntimeConfig config)
    {
        config.HostPort = NormalizePort(config.HostPort);
        config.JoinPort = NormalizePort(config.JoinPort);
        config.PlayerId = NormalizePlayerId(config.PlayerId);
        config.PlayerIdText = string.IsNullOrWhiteSpace(config.PlayerIdText)
            ? (config.PlayerId > 1 ? config.PlayerId.ToString() : "")
            : config.PlayerIdText.Trim();
        config.JoinIp = string.IsNullOrWhiteSpace(config.JoinIp) ? "127.0.0.1" : config.JoinIp.Trim();
    }

    private static void EnsureAutoGeneratedPlayerId()
    {
        if (Current.PlayerId > 1 && Current.PlayerId != 1000UL)
        {
            return;
        }

        Current.PlayerId = GeneratePlayerId();
        Save();
        MainFile.Logger.Info($"Generated beta direct-connect player ID: {Current.PlayerId}");
    }

    private static ulong? GetCommandLinePlayerId()
    {
        if (CommandLineHelper.TryGetValue("clientId", out string value) &&
            ulong.TryParse(value, out ulong playerId))
        {
            playerId = NormalizePlayerId(playerId);
            if (playerId > 0)
            {
                return playerId;
            }
        }

        return null;
    }

    private static ulong GeneratePlayerId()
    {
        return (ulong)RandomNumberGenerator.GetInt32(10000, 99999999);
    }

    public static ulong ParsePlayerIdInput(string input)
    {
        string normalized = string.IsNullOrWhiteSpace(input) ? string.Empty : input.Trim();
        if (string.IsNullOrEmpty(normalized))
        {
            return 0UL;
        }

        if (ulong.TryParse(normalized, out ulong numericPlayerId))
        {
            return NormalizePlayerId(numericPlayerId);
        }

        byte[] bytes = SHA256.HashData(Encoding.UTF8.GetBytes(normalized));
        ulong hashedPlayerId = BitConverter.ToUInt64(bytes, 0);
        if (BitConverter.IsLittleEndian)
        {
            hashedPlayerId = System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(hashedPlayerId);
        }

        hashedPlayerId &= 0x7FFFFFFFFFFFFFFFUL;
        if (hashedPlayerId <= 1UL)
        {
            hashedPlayerId += 2UL;
        }

        return hashedPlayerId;
    }

    public static bool IsNumericPlayerIdText(string input)
    {
        return !string.IsNullOrWhiteSpace(input) && ulong.TryParse(input.Trim(), out _);
    }

    private static string GetModDirectory()
    {
        string? location = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
        return string.IsNullOrWhiteSpace(location) ? AppContext.BaseDirectory : location;
    }
}
