"""
STS2 Mod Development Knowledge Base
------------------------------------
Based on actual working examples and local documentation.
Used by Code Agent and Planner to avoid looking up basics from scratch.

Sources:
- E:/STS2mod/docs/ (local verified docs with real bugs & solutions)
- https://github.com/lamali292/sts2_example_mod
- https://github.com/Alchyr/BaseLib-StS2
- sts2_api_reference.md (decompiled from sts2.dll, ilspycmd v9.1.0)
"""
from __future__ import annotations

from pathlib import Path

# Full path to the decompiled API reference (same directory as this file)
API_REF_PATH = Path(__file__).parent / "sts2_api_reference.md"

# BaseLib decompiled source — committed to repo, always available
# Generated by: ilspycmd BaseLib.dll --outputdir backend/agents/baselib_src/
BASELIB_SRC_PATH = Path(__file__).parent / "baselib_src" / "BaseLib.decompiled.cs"


def _load_api_reference() -> str:
    """Load the decompiled API reference markdown. Returns empty string if missing."""
    try:
        return API_REF_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


# ── Common knowledge (injected for every asset type) ─────────────────────────

_COMMON_DOCS = """
# STS2 (Slay the Spire 2) Mod Development Reference

## Build Command
**ALWAYS use `dotnet publish`**, NOT `dotnet build`.
- `dotnet publish` = compiles DLL + exports Godot PCK + deploys both to the game's mods folder.
- `dotnet build` = only compiles DLL, no PCK export. Game won't load the mod.
- Game requires BOTH `.dll` AND `.pck` in `STS2GamePath/mods/<ModName>/`.

## How the Game Loads Mods
- On startup, the game scans `STS2GamePath/mods/` for subdirectories.
- A mod is recognized when the subdirectory contains BOTH `<ModName>.dll` AND `<ModName>.pck`.
- `.pck` contains `mod_manifest.json` (mod identity) and all image/localization assets.
- `.pck` format is version-locked to the Godot engine version: must use **Godot 4.5.1 Mono**.
  Using a newer Godot produces "Pack created with a newer version of the engine" error.

## Project Structure
```
MyMod/
├── local.props              ← local machine paths (NOT committed to git)
├── MyMod.csproj             ← project file
├── MainFile.cs              ← (or ModEntry.cs) mod entry point
├── Cards/
│   └── DarkBlade.cs
├── Relics/
│   └── MyRelic.cs
├── Extensions/
│   └── StringExtensions.cs  ← image path helpers
└── <ModName>/               ← Godot resource root (SAME NAME as mod)
    ├── mod_image.png
    ├── images/
    │   ├── card_portraits/
    │   │   ├── DarkBlade.png      (250×190)
    │   │   └── big/
    │   │       └── DarkBlade.png  (1000×760)
    │   └── relics/
    │       ├── my_relic.png           (icon)
    │       ├── my_relic_outline.png   (icon outline)
    │       └── big/
    │           └── my_relic.png       (large icon)
    └── localization/
        ├── eng/
        │   ├── relics.json
        │   └── cards.json
        └── zhs/              ← Simplified Chinese (optional, falls back to eng if absent)
            ├── relics.json
            └── cards.json
```

NOTE: The Godot resource directory is `<ModName>/<ModName>/...` — the mod name appears TWICE in the path.

## Localization Language Codes
Game-supported 3-letter codes: `eng`, `zhs` (Simplified Chinese), `deu`, `esp`, `fra`, `ita`, `jpn`, `kor`, `pol`, `ptb`, `rus`, `spa`, `tha`, `tur`.
- Mod path loaded by game: `res://{mod_id}/localization/{language}/{table}.json`
- If a language folder is absent from a mod, the game **automatically falls back to `eng/`**.
- Always provide at least `eng/`. Add `zhs/` for Chinese players.
Images must be placed under `project_root/<ModName>/images/...`, NOT `project_root/images/...`.

## local.props (required, never commit)
```xml
<Project>
  <PropertyGroup>
    <STS2GamePath>C:/SteamLibrary/.../Slay the Spire 2</STS2GamePath>
    <GodotExePath>C:/tools/Godot_v4.5.1-stable_mono_win64.exe</GodotExePath>
  </PropertyGroup>
</Project>
```

## Mod Entry Point
```csharp
[ModInitializer("Initialize")]
public class MainFile   // (some templates use ModEntry — read the existing file name)
{
    public static string ModId => "MyMod";   // must match assembly/folder name

    public static void Initialize()
    {
        var harmony = new Harmony("com.yourname.mymod");
        harmony.PatchAll();   // auto-applies all [HarmonyPatch] classes in assembly
    }
}
```

## Harmony Patching
```csharp
using HarmonyLib;

// In Initialize():
var harmony = new Harmony("com.yourname.modname");
harmony.PatchAll();  // finds all [HarmonyPatch] classes automatically

// Patch example:
[HarmonyPatch(typeof(SomeGameClass), "MethodName")]
public class MyPatch
{
    // Prefix: runs before the original method
    static bool Prefix(SomeGameClass __instance, ref int __result) { return true; }
    // Postfix: runs after the original method
    static void Postfix(SomeGameClass __instance, ref int __result) { }
}
```

## Common Gotchas Summary
1. `[Pool]` missing on card → crash: `must be marked with a PoolAttribute`
2. `ShouldReceiveCombatHooks` missing on relic → combat hooks silently don't fire
3. Relic localization missing → entire relic encyclopedia list appears empty (vanilla + mod)
4. `dotnet build` instead of `dotnet publish` → DLL only, PCK not updated, mod not loaded
5. Godot version != 4.5.1 → `Pack created with a newer version` error
6. Image placed at `project_root/images/...` instead of `project_root/<ModName>/images/...` → black card art
7. Game running during build → DLL locked, build fails
8. Card constructor uses `baseCost:` named parameter (NOT `cost:`) → compile error CS1739
9. Upgrade check: `IsUpgraded` (bool property), NOT `UpgradeLevel` (int) → compile error or wrong behavior
10. `new XxxModel()` → `DuplicateModelException` → black screen on run start; always use `ModelDb.Relic<T>().ToMutable()` etc.
11. Localization JSON must be **flat key-value**, NOT nested objects. `{"FOO.title": "Bar"}` ✅  `{"FOO": {"title": "Bar"}}` ❌ → `LocException: token type 'StartObject' as a string` → game crashes on startup.
    Localization text must NOT contain square brackets `[]` — the game's rich text renderer parses them as BBCode tags. `[MyTag]` text becomes an unclosed BBCode open tag → rendering exception → event state machine hangs, game gets stuck. Use `()`, `{}`, or plain text instead. `{"FOO.title": "Bar"}` ✅  `{"FOO": {"title": "Bar"}}` ❌ → `LocException: token type 'StartObject' as a string` → game crashes on startup.
12. `FromSimpleGridForRewards` / `FromSimpleGrid` work OUTSIDE combat (in events, Neow callbacks). The `CombatManager.IsEnding` check only early-returns during combat teardown, not a requirement for combat to exist. BrainLeech event uses this in a non-combat context.
13. `CardSelectCmd.FromChooseACardScreen` max 3 cards only — passing >3 throws ArgumentException. For showing many cards use `FromSimpleGridForRewards` instead.
14. Card localization key format is `{RootNS.ToUpperInvariant()}-{Slugify(ClassName)}.title`. The prefix is simple `.ToUpperInvariant()` (NO CamelCase splitting via Slugify). Example: `S08_FuseCharge.Cards` → prefix `S08_FUSECHARGE-`, class `FuseCharge` → `FUSE_CHARGE` → full key `S08_FUSECHARGE-FUSE_CHARGE.title`. Wrong: `S08_FUSE_CHARGE-FUSE_CHARGE` ❌  Wrong: `FUSE_CHARGE.title` ❌  Wrong: `.name` suffix ❌
15. Custom Neow/event option callbacks MUST call `SetEventFinished(LocString)` at the end, or the event state machine never advances — player sees no "Continue" button and is permanently stuck. `SetEventFinished` is `protected` on `EventModel`, so call via reflection:
    ```csharp
    typeof(EventModel).GetMethod("SetEventFinished",
        BindingFlags.NonPublic | BindingFlags.Instance)
        ?.Invoke(eventInstance, new object[] { new LocString("relics", "MY_KEY.title") });
    ```

## Built-in powers (MegaCrit.Sts2.Core.Models.Powers)
Do NOT redefine any of these — use them directly.
`using MegaCrit.Sts2.Core.Models.Powers;`

```csharp
// Generic pattern (same for all powers):
await PowerCmd.Apply<TPower>(target, amount, ownerCreature, cardSource);
bool has = creature.HasPower<TPower>();
int stacks = (int)creature.GetPower<TPower>().Amount;
```

**Common debuffs (Debuff | Counter unless noted):**
| Class | Effect |
|---|---|
| `PoisonPower` | Loses HP = stack count at turn end, then decrements |
| `VulnerablePower` | Takes 50% more damage |
| `WeakPower` | Deals 25% less damage |
| `FrailPower` | Gains 25% less block |
| `SlowPower` | Loses energy or slows action |
| `ConstrictPower` | Constriction damage per turn |
| `NoBlockPower` | Cannot gain block |

**Common buffs (Buff | Counter unless noted):**
| Class | Effect |
|---|---|
| `StrengthPower` | +N damage on attacks (can be negative) |
| `DexterityPower` | +N block on block cards (can be negative) |
| `ThornsPower` | Deals N damage when attacked |
| `RegenPower` | Heals N HP at turn end, then decrements |
| `ArtifactPower` | Negates next N debuffs |
| `IntangiblePower` | All damage reduced to 1 per hit |
| `PlatingPower` | Permanent block that persists between turns |
| `BarricadePower` | Block is never cleared at turn end (Buff | Single) |
| `BlurPower` | Block is not cleared at turn end this turn |
| `VigorPower` | Next attack deals +N damage (consumed on use) |
| `RagePower` | Gain N block each time a card is played |
| `EnragePower` | Gain N strength each time a skill is played |
| `LethalityPower` | Applies extra poison when poison is applied |
| `FocusPower` | +N to orb/passive effect power (Defect) |
| `RitualPower` | Gains N strength at turn end |
| `EnvenomPower` | Applies N poison when unblocked damage is dealt |
| `RupturePower` | Gains N strength when HP is lost from a card |
| `FeelNoPainPower` | Gains N block when a card is exhausted |
| `DarkEmbracePower` | Draws N cards when a card is exhausted |
| `NightmarePower` | Creates N copies of target card in hand next turn |
| `EchoFormPower` | First card each turn is played twice |
| `DuplicationPower` | Next card is played twice |
| `BurstPower` | Next N skills are played twice |
| `CorruptionPower` | Skills cost 0 but Exhaust (Buff | Single) |
| `CurlUpPower` | Gains N block when HP is reduced below threshold |
| `MayhemPower` | Auto-plays top card of draw pile at turn start |

## Debugging
Game logs: `%AppData%/SlayTheSpire2/logs/godot.log`
Key search terms: `[ERROR]`, `Finished mod initialization for` (confirms mod loaded)
"""

# ── Type-specific API snippets ────────────────────────────────────────────────

_CARD_DOCS = """
## Cards

### Base class: CustomCardModel
```csharp
using BaseLib.Abstracts;
using BaseLib.Utils;                               // PoolAttribute
using MegaCrit.Sts2.Core.Commands;                // DamageCmd
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer; // PlayerChoiceContext
using MegaCrit.Sts2.Core.Localization.DynamicVars;// DamageVar, BlockVar
using MegaCrit.Sts2.Core.Models.CardPools;        // IroncladCardPool, SilentCardPool, etc.
using MegaCrit.Sts2.Core.ValueProps;              // ValueProp

namespace MyMod.Cards;

[Pool(typeof(IroncladCardPool))]              // REQUIRED — crashes without it
public class DarkBlade() : CustomCardModel(
    baseCost: 1,                              // ← named parameter is "baseCost" (NOT "cost")
    type: CardType.Attack,
    rarity: CardRarity.Common,
    target: TargetType.AnyEnemy)
{
    // Declare damage/block values here — engine reads them for card description too
    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DamageVar(8m, ValueProp.Move)];   // 8 base damage, scales with Strength

    public override string PortraitPath       => "DarkBlade.png".CardImagePath();
    public override string CustomPortraitPath => "DarkBlade.png".BigCardImagePath();
    public override string BetaPortraitPath   => "DarkBlade.png".CardImagePath();

    // Dealing damage — use DamageCmd.Attack, never call GainHp/LoseHp directly
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        ArgumentNullException.ThrowIfNull(cardPlay.Target, "cardPlay.Target");
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .Targeting(cardPlay.Target)
            .Execute(choiceContext);
    }

    // Turn-end-in-hand effect (MUST also override HasTurnEndInHandEffect => true)
    public override bool HasTurnEndInHandEffect => true;
    public override async Task OnTurnEndInHand(PlayerChoiceContext choiceContext)
    {
        await base.OnTurnEndInHand(choiceContext);
    }

    // Upgrade logic — use IsUpgraded (NOT UpgradeLevel, NOT Level)
    protected override void OnUpgrade()
    {
        base.DynamicVars.Damage.UpgradeValueBy(3m);   // 8 → 11
    }
    // Read upgrade state anywhere: if (IsUpgraded) { ... }
}
```

### DamageCmd — the only correct way to deal damage from a card
```csharp
// Single target (AnyEnemy / RandomEnemy)
await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
    .FromCard(this)
    .Targeting(cardPlay.Target)
    .Execute(choiceContext);

// All enemies (TargetType.AllEnemies) — iterate CombatState.Enemies
// cardPlay.Target is null for AllEnemies; read enemies from context instead

// Random opponent (no specific target needed — use with TargetType.None)
await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
    .FromCard(this)
    .TargetingRandomOpponents(base.CombatState!)   // picks one random living enemy
    .Execute(choiceContext);

// Multi-hit (plays N times):
await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
    .FromCard(this)
    .Targeting(cardPlay.Target)
    .WithHitCount(IsUpgraded ? 2 : 1)              // hit N times
    .Execute(choiceContext);

// X-cost cards: read captured X from energy
int xValue = base.DynamicVars.XValue.BaseValue;   // or EnergyCost.CapturedXValue

// With hit visual effect (optional):
await DamageCmd.Attack(dmg).FromCard(this).Targeting(target)
    .WithHitFx("vfx/vfx_attack_slash")
    .Execute(choiceContext);
```

### Cross-card shared state (e.g. "combo counter")
```csharp
// Static counter class — plain static, no Harmony needed
public static class ComboCounter
{
    public static int Count { get; private set; }
    public static void Increment() => Count++;
    public static void Reset() => Count = 0;
}

// Reset at turn end — override AfterTurnEnd on any card in the project.
// AfterTurnEnd fires on ALL cards in ANY combat pile (Draw/Hand/Discard/Exhaust).
// side == CombatSide.Player means it's the player's turn ending.
public override Task AfterTurnEnd(PlayerChoiceContext choiceContext, CombatSide side)
{
    if (side == CombatSide.Player) ComboCounter.Reset();
    return base.AfterTurnEnd(choiceContext, side);
}
// Also reset on AfterCombatEnd to avoid state leaking between fights.
public override Task AfterCombatEnd(CombatRoom room)
{
    ComboCounter.Reset();
    return base.AfterCombatEnd(room);
}
```

### DynamicVar types and live card numbers
All values shown on the card face must be declared as `DynamicVar` in `CanonicalVars`. The engine
automatically recalculates and shows updated values (e.g. 4 instead of 6 when Weakened).
- `DamageVar(baseValue, ValueProp.Move)` — scales with Strength/Weak/Vulnerable; accessed as `base.DynamicVars.Damage`
- `BlockVar(baseValue, ValueProp.Move)` — scales with Dexterity/Frail; accessed as `base.DynamicVars.Block`
- `PowerVar<T>(baseValue)` — amount for a power (e.g. poison stacks); accessed by name e.g. `base.DynamicVars["PoisonPower"]`
- `XVar(...)` — for X-cost cards

**Always** use `base.DynamicVars.Damage.BaseValue` (not a hardcoded literal) when calling DamageCmd.

```csharp
// Card that deals damage AND applies poison — full CanonicalVars + ExtraHoverTips pattern:
using MegaCrit.Sts2.Core.Localization.DynamicVars; // DamageVar, PowerVar
using MegaCrit.Sts2.Core.Models.Powers;            // PoisonPower
using MegaCrit.Sts2.Core.HoverTips;               // HoverTipFactory

protected override IEnumerable<DynamicVar> CanonicalVars =>
    [new DamageVar(6m, ValueProp.Move), new PowerVar<PoisonPower>(3m)];

// Keyword tooltip: shows "Poison" as a linked keyword on the card
protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [HoverTipFactory.FromPower<PoisonPower>()];

// In OnPlay:
await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue).FromCard(this).Targeting(cardPlay.Target).Execute(choiceContext);
await PowerCmd.Apply<PoisonPower>(cardPlay.Target, base.DynamicVars["PoisonPower"].BaseValue, base.Owner.Creature, this);

// Upgrade:
protected override void OnUpgrade()
{
    base.DynamicVars.Damage.UpgradeValueBy(2m);
    base.DynamicVars["PoisonPower"].UpgradeValueBy(1m);
}
```

### Localization with dynamic values
Use `{VarName}` placeholders in description text — the engine substitutes the live computed value.
Variable names: `Damage` (DamageVar), `Block` (BlockVar), `PoisonPower` (PowerVar\<PoisonPower\>), etc.

```json
{
  "MY_MOD-BLOOD_LANCE.description": "造成 {Damage} 点伤害。施加 {PoisonPower} 层[毒]。",
  "MY_MOD-BLOOD_LANCE.upgrade_description": "造成 {Damage} 点伤害。施加 {PoisonPower} 层[毒]。"
}
```
- `{Damage}` renders the live value (already modified by Weak/Strength etc.)
- `[毒]` or `[Poison]` renders the keyword with tooltip (BBCode-style tag the game supports for keyword highlighting — this is different from `[]` used in plain text which must be avoided)
- Do NOT hardcode numbers in localization if a `DynamicVar` exists for that value — use `{VarName}` instead

### ExtraHoverTips — keyword tooltips on the card
```csharp
// Single power keyword:
protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [HoverTipFactory.FromPower<PoisonPower>()];

// Multiple power keywords:
protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [HoverTipFactory.FromPower<VulnerablePower>(), HoverTipFactory.FromPower<WeakPower>()];
```

### Card mechanic keywords (CanonicalKeywords)
These appear as highlighted keyword banners on the card. Use `CanonicalKeywords` property:
```csharp
using MegaCrit.Sts2.Core.Entities.Cards;  // CardKeyword

// Single keyword:
public override IEnumerable<CardKeyword> CanonicalKeywords =>
    [CardKeyword.Exhaust];

// Multiple keywords:
public override IEnumerable<CardKeyword> CanonicalKeywords =>
    [CardKeyword.Exhaust, CardKeyword.Innate];

// Add a keyword on upgrade:
protected override void OnUpgrade()
{
    AddKeyword(CardKeyword.Retain);
    base.DynamicVars.Damage.UpgradeValueBy(3m);
}
```

| `CardKeyword` value | Meaning |
|---|---|
| `Exhaust` | Removed from play (sent to exhaust pile) after played |
| `Ethereal` | Removed from hand at end of turn if not played |
| `Innate` | Starts in opening hand each combat |
| `Retain` | NOT discarded at end of turn |
| `Sly` | Appears in hand after the first turn (delayed draw) |
| `Eternal` | Stays in hand even after played |
| `Unplayable` | Cannot be played (effect card / curse) |

Displayed order: Ethereal/Sly/Retain/Innate/Unplayable shown **before** description; Exhaust/Eternal shown **after**.

### Power keywords on cards (ExtraHoverTips)
To show a power name as a linked keyword tooltip on the card face, override `ExtraHoverTips`:
```csharp
using MegaCrit.Sts2.Core.HoverTips;  // HoverTipFactory, IHoverTip

// Single power keyword:
protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [HoverTipFactory.FromPower<PoisonPower>()];

// Multiple power keywords:
protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [HoverTipFactory.FromPower<VulnerablePower>(), HoverTipFactory.FromPower<WeakPower>()];
```
Without this, the power name in the card description is plain text with no tooltip.

### Card pools — choose based on which character should get this card
All pools are in `MegaCrit.Sts2.Core.Models.CardPools`. Pick the pool matching the card's theme/character:

| Pool class | Character | Theme |
|---|---|---|
| `IroncladCardPool` | Ironclad | Strength, block, self-damage, exhaust |
| `SilentCardPool` | Silent | Poison, shivs, agility, discard |
| `DefectCardPool` | Defect | Orbs, focus, lightning/frost/dark/plasma |
| `RegentCardPool` | Regent | Stances, mantras, divine/wrath/calm |
| `NecrobinderCardPool` | Necrobinder | Undead, summoning, death effects |
| `ColorlessCardPool` | All characters | Truly universal (no character affinity) |
| `CurseCardPool` | — | Curse cards only |
| `StatusCardPool` | — | Status cards only |

**Choose `ColorlessCardPool` ONLY if the card genuinely fits all characters equally.**
For any card with a thematic or mechanical affinity to a character, use that character's pool.

**If this card belongs to a NEW/CUSTOM mod character** (not one of the 5 above), that character
needs its own pool class. Name it after the character (e.g. character "Diaosi" → `DiaosiCardPool`).

```csharp
// File: YourMod/CardPools/DiaosiCardPool.cs
using BaseLib.Abstracts;
using Godot;
namespace YourMod.CardPools;

public class DiaosiCardPool : CustomCardPoolModel
{
    // Title: unique string ID (lowercase, no spaces)
    public override string Title => "diaosi";

    // IsColorless: false for character-specific pools
    public override bool IsColorless => false;

    // Card frame shape — must be one of the built-in material names:
    //   "card_frame_red"      (Ironclad)
    //   "card_frame_green"    (Silent)
    //   "card_frame_blue"     (Defect)
    //   "card_frame_orange"   (Regent)
    //   "card_frame_pink"     (Necrobinder)
    //   "card_frame_colorless", "card_frame_curse", "card_frame_quest"
    // Custom mod characters typically reuse one of these or use ShaderColor to recolor.
    public override string CardFrameMaterialPath => "card_frame_red";

    // ShaderColor: HSV recolors card_frame_red to any color.
    // Override this to give the character a distinct card color without needing a new material.
    // new Color("RRGGBBAA") in hex. Example: purple tint:
    public override Color ShaderColor => new Color("9B59B6FF");

    // DeckEntryCardColor: color dot shown next to the card in the deck list UI
    public override Color DeckEntryCardColor => new Color("9B59B6FF");
}
```

Then use `[Pool(typeof(DiaosiCardPool))]` on all cards for that character.
The character class must also have `public override CardPoolModel CardPool => ModelDb.CardPool<DiaosiCardPool>();`
If the mod already has a pool class defined, reuse it — do NOT create a duplicate.

### CRITICAL: [Pool] attribute is mandatory
- `CustomCardModel` has `autoAdd=true` by default — BaseLib auto-registers the card to its pool.
- But it MUST know WHICH pool via `[Pool(typeof(SomeCardPool))]`.
- **Missing [Pool] → game crashes on startup**: `Model X must be marked with a PoolAttribute`
- Do NOT create a Harmony patch to add cards to pools. BaseLib handles this automatically.

### Key enums
- `CardType`: Attack, Skill, Power, Status, Curse, Quest
- `CardRarity`: None, Basic, Common, Uncommon, Rare, Ancient, Event, Token, Status, Curse, Quest
- `TargetType`: None, Self, AnyEnemy, AllEnemies, RandomEnemy, AnyPlayer, AnyAlly, AllAllies, TargetedNoCreature, Osty

### StringExtensions.cs (image path helpers — check if already exists, add if not)
```csharp
namespace MyMod.Extensions;
public static class StringExtensions
{
    public static string CardImagePath(this string path) =>
        Path.Join(MainFile.ModId, "images", "card_portraits", path);

    public static string BigCardImagePath(this string path) =>
        Path.Join(MainFile.ModId, "images", "card_portraits", "big", path);
}
```

### Card Localization
Always create BOTH `eng/` and `zhs/` (Simplified Chinese) localization files.

**pack/MyMod/localization/eng/cards.json**
```json
{
  "MY_MOD-DARK_BLADE.title": "Dark Blade",
  "MY_MOD-DARK_BLADE.description": "Deal {Damage} damage.",
  "MY_MOD-DARK_BLADE.upgrade_description": "Deal {Damage} damage."
}
```

**pack/MyMod/localization/zhs/cards.json**
```json
{
  "MY_MOD-DARK_BLADE.title": "暗黑匕首",
  "MY_MOD-DARK_BLADE.description": "造成 {Damage} 点伤害。",
  "MY_MOD-DARK_BLADE.upgrade_description": "造成 {Damage} 点伤害。"
}
```

**CRITICAL: Use `{VarName}` placeholders, NOT hardcoded numbers.**
- `{Damage}` → live damage value (updates when Weakened/Strengthened)
- `{Block}` → live block value (updates when Frail/Dexterity)
- `{PoisonPower}` → live poison stacks from `PowerVar<PoisonPower>`
- Both `.description` and `.upgrade_description` use the same `{VarName}` — the engine shows the upgraded BaseValue automatically.
- Do NOT write `[red]8[/red]` with a literal number if a DynamicVar exists for it.
Key format: `{Prefix}-{Slugify(ClassName)}.suffix`
- Prefix = `t.Namespace.Substring(0, firstDot).ToUpperInvariant()` — simple uppercase of root namespace, NO CamelCase splitting
  - `S08_FuseCharge.Cards` → root `S08_FuseCharge` → ToUpperInvariant → `S08_FUSECHARGE` (NOT `S08_FUSE_CHARGE`)
  - `S09_Arcanist.Cards` → root `S09_Arcanist` → `S09_ARCANIST`
- ClassName: Slugify (CamelCase → UPPER_SNAKE_CASE): `FuseCharge` → `FUSE_CHARGE`
- Suffix: `.title` for card name, `.description`, `.upgrade_description`
- Keys are identical across languages; only values differ.
- Example: class `FuseCharge` in namespace `S08_FuseCharge.Cards` → key `S08_FUSECHARGE-FUSE_CHARGE`
"""

_RELIC_DOCS = """
## Relics

### Base class: CustomRelicModel (BaseLib wrapper — auto-registers to pool)
```csharp
using BaseLib.Abstracts;      // CustomRelicModel
using BaseLib.Utils;          // PoolAttribute
using MegaCrit.Sts2.Core.Entities.Relics;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.RelicPools;  // SharedRelicPool
using MegaCrit.Sts2.Core.Runs;               // IRunState

namespace MyMod.Relics;

[Pool(typeof(SharedRelicPool))]               // auto-adds to relic reward pool
public sealed class FangedGrimoire : CustomRelicModel
{
    public override RelicRarity Rarity => RelicRarity.Common;
    public override bool IsAllowed(IRunState runState) => true;

    // REQUIRED for combat hooks to fire
    public override bool ShouldReceiveCombatHooks => true;

    // Image paths (relative inside .pck — no leading slash)
    public override string PackedIconPath           => "MyMod/images/relics/fanged_grimoire.png";
    protected override string PackedIconOutlinePath => "MyMod/images/relics/fanged_grimoire_outline.png";
    protected override string BigIconPath           => "MyMod/images/relics/big/fanged_grimoire.png";

    // All hook methods are virtual Task (default returns Task.CompletedTask).
    // Full list of 60+ hooks in sts2_api_reference.md (AbstractModel section).
    public override Task AfterDamageGiven(
        PlayerChoiceContext choiceContext,
        Creature? dealer,
        DamageResult result,
        ValueProp props,
        Creature target,
        CardModel? cardSource)
    {
        if (dealer?.IsPlayer == true && result.TotalDamage > 0)
        {
            dealer.GainBlockInternal(2);
            Flash();   // plays the relic flash animation
        }
        return Task.CompletedTask;
    }
}
```

### Key enums
- `RelicRarity`: None, Starter, Common, Uncommon, Rare, Shop, Event, Ancient

### CRITICAL: `ShouldReceiveCombatHooks => true` — without this, all combat hooks silently never fire.
### `Flash()` — plays the relic glowing animation (always call when the relic triggers).

### Pool registration — NO Harmony patch needed
`CustomRelicModel` (BaseLib) calls `CustomContentDictionary.AddModel()` in its constructor.
Combined with `[Pool(typeof(SharedRelicPool))]`, the relic is automatically added to the
shared relic reward pool. **Do NOT write a RelicPoolPatch** — it's redundant and was a
common mistake in older guides.

### Relic Localization — CRITICAL (missing crashes the entire relic encyclopedia list)
Key naming: CamelCase class name → UPPER_SNAKE_CASE (e.g. `FangedGrimoire` → `FANGED_GRIMOIRE`)
Always create BOTH `eng/` and `zhs/` files.

**pack/MyMod/localization/eng/relics.json**
```json
{
  "FANGED_GRIMOIRE.title": "Fanged Grimoire",
  "FANGED_GRIMOIRE.description": "Whenever you deal damage, gain [blue]2[/blue] Block.",
  "FANGED_GRIMOIRE.flavor": "A tome that feeds on violence."
}
```

**pack/MyMod/localization/zhs/relics.json**
```json
{
  "FANGED_GRIMOIRE.title": "獠牙魔典",
  "FANGED_GRIMOIRE.description": "每当你造成伤害时，获得 [blue]2[/blue] 点格挡。",
  "FANGED_GRIMOIRE.flavor": "一本以暴力为食的典籍。"
}
```
ALL custom relics must have .title, .description, and optionally .flavor entries.
"""

_POWER_DOCS = """
## Powers (Buffs / Debuffs)

### IMPORTANT: Base class is PowerModel directly — there is NO CustomPowerModel
Unlike relics (CustomRelicModel), powers extend `PowerModel` from sts2.dll directly.
Do NOT search for CustomPowerModel — it does not exist.

### Canonical example: EnragePower (triggers on Skill cards, applies Strength)
```csharp
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;

namespace MyMod.Powers;

public sealed class MyBuff : PowerModel
{
    // REQUIRED abstract properties
    public override PowerType Type => PowerType.Buff;            // or Debuff
    public override PowerStackType StackType => PowerStackType.Counter; // or Single

    // Trigger on Attack cards played:
    public override async Task AfterCardPlayed(PlayerChoiceContext context, CardPlay cardPlay)
    {
        if (cardPlay.Card.Type == CardType.Attack)  // Attack | Skill | Power | Status | Curse
        {
            // Deal extra damage to target using CreatureCmd
            await CreatureCmd.Damage(context, cardPlay.Target, Amount, ValueProp.Unpowered, Owner, null);
        }
        // No base call needed unless you want other powers to chain
    }

    // Duration-style: tick down each turn end, auto-removed when Amount reaches 0
    public override async Task AfterTurnEnd(PlayerChoiceContext choiceContext, CombatSide side)
    {
        await PowerCmd.TickDownDuration(this);  // decrements by 1, removes if 0
    }
}
```

### Canonical example: JuggernautPower (triggers on Block, damages random enemy)
```csharp
public override async Task AfterBlockGained(Creature creature, decimal amount, ValueProp props, CardModel? cardSource)
{
    if (amount > 0m && creature == Owner)
    {
        var enemies = CombatState.HittableEnemies;
        if (enemies.Count > 0)
        {
            Creature target = Owner.Player.RunState.Rng.CombatTargets.NextItem(enemies);
            Flash();  // visual flash on relic/power icon
            await CreatureCmd.Damage(new ThrowingPlayerChoiceContext(), target, Amount, ValueProp.Unpowered, Owner, null);
        }
    }
}
```

### Applying this power from a Card or Relic
```csharp
// Apply 3 stacks of MyBuff to the player (Owner is the creature receiving it)
await PowerCmd.Apply<MyBuff>(target, 3m, applier, cardSource);

// Tick down a power's duration (decrements by 1, removes at 0)
await PowerCmd.TickDownDuration(this);

// Remove a power immediately
await PowerCmd.Remove(this);
```

### Key enums
- `PowerType`: None, Buff, Debuff  (MegaCrit.Sts2.Core.Entities.Powers)
- `PowerStackType`: None, Counter, Single  (same namespace)
- `CardType`: Attack, Skill, Power, Status, Curse  (MegaCrit.Sts2.Core.Entities.Cards)

### Power image paths (raw PNG, NOT atlas)
```
<ModName>/images/powers/<PowerName>.png       (small icon, e.g. 48×48)
<ModName>/images/powers/big/<PowerName>.png   (large, e.g. 192×192)
```
Use these as the icon path string in your Power's image registration, same format as relics.

### Power Localization
Table name: `"powers"`. Keys: `<id>.title`, `<id>.description`.
Create both `eng/powers.json` and `zhs/powers.json`.
```json
{ "BlazePower": { "title": "Blaze", "description": "At the start of your turn, deal !A! damage." } }
```

### Full PowerModel hooks → see sts2_api_reference.md
Common hooks: AfterCardPlayed, AfterBlockGained, AfterTurnEnd, AfterDamageGiven,
AfterDamageReceived, AfterCombatEnd, BeforeAttack, AfterAttack
"""

_POTION_DOCS = """
## Potions

### IMPORTANT: CustomPotionModel is in BaseLib — NOT in decompiled_tmp
Do NOT search decompiled_tmp for CustomPotionModel. It lives in BaseLib.
Source: https://github.com/Alchyr/BaseLib-StS2/blob/master/Abstracts/CustomPotionModel.cs

### Base class: CustomPotionModel
```csharp
using BaseLib.Abstracts;        // CustomPotionModel
using BaseLib.Utils;            // PoolAttribute
using MegaCrit.Sts2.Core.Commands;          // PowerCmd, CreatureCmd
using MegaCrit.Sts2.Core.Entities.Cards;   // TargetType
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Potions; // PotionRarity, PotionUsage
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models.Powers;    // StrengthPower etc.
using MegaCrit.Sts2.Core.Models.PotionPools; // SharedPotionPool
using MegaCrit.Sts2.Core.ValueProps;

namespace MyMod.Potions;

[Pool(typeof(SharedPotionPool))]            // appears in the potion reward pool
public class BerserkerBrew : CustomPotionModel
{
    public override PotionRarity Rarity   => PotionRarity.Common;
    public override PotionUsage  Usage    => PotionUsage.CombatOnly;  // or AnyTime
    public override TargetType   TargetType => TargetType.Self;        // or AnyEnemy

    // Conditional use (property, NOT a method) — return false to grey out
    public override bool PassesCustomUsabilityCheck => Owner.Creature.CurrentHp > 8;

    // Effect method — override OnUse (NOT Use, NOT OnApply)
    protected override async Task OnUse(PlayerChoiceContext choiceContext, Creature? target)
    {
        // Apply 3 Strength to self
        await PowerCmd.Apply<StrengthPower>(Owner.Creature, 3m, Owner.Creature, null);

        // Deal 8 unblockable damage to self (bypasses block)
        await CreatureCmd.Damage(choiceContext, Owner.Creature, 8m, ValueProp.Unblockable, null, null);
    }
}
```

### Potion localization key format
BaseLib derives the loc key prefix from the root namespace via `TypePrefix.GetPrefix(type)`.
Pattern: `{NAMESPACE_ROOT}-{CLASS_NAME}` in UPPER_SNAKE_CASE.
Example: namespace `S07_BerserkerBrew.Potions` → class `BerserkerBrew` → key prefix `S07_BERSERKERBREW-BERSERKER_BREW`

**localization/eng/potions.json**
```json
{
  "S07_BERSERKERBREW-BERSERKER_BREW.title": "Berserker Brew",
  "S07_BERSERKERBREW-BERSERKER_BREW.description": "Gain [blue]3[/blue] Strength. Lose [red]8[/red] HP."
}
```
Also create `zhs/potions.json` with the same keys.

### Potion image path
`<ModName>/images/potions/<ClassName>.png`  (single image, no separate big/ variant needed)

### Key enums
- `PotionRarity`: Common, Uncommon, Rare
- `PotionUsage`: CombatOnly, AnyTime, OutsideCombat
"""

_CHARACTER_DOCS = """
## New Character (Full Architecture)

Creating a new playable character requires FIVE components:
1. `ArcanistCardPool : CustomCardPoolModel`    — card pool
2. `ArcanistRelicPool : CustomRelicPoolModel`  — relic pool
3. `ArcanistPotionPool : CustomPotionPoolModel`— potion pool
4. Cards (CustomCardModel) + Relics (CustomRelicModel)
5. `Arcanist : PlaceholderCharacterModel`      — character model

### PlaceholderCharacterModel (use this for placeholder art — reuses existing character assets)
```csharp
using BaseLib.Abstracts;    // PlaceholderCharacterModel
using Godot;
using MegaCrit.Sts2.Core.Entities.Characters;
using MegaCrit.Sts2.Core.Models;

namespace MyMod.Characters;

public sealed class Arcanist : PlaceholderCharacterModel
{
    // Reuses Ironclad's art for all visual assets (portrait, select screen bg, energy icon, etc.)
    public override string PlaceholderID => "ironclad";   // or "silent", "defect" etc.

    public override Color NameColor => new Color("8B5CF6");  // Godot hex color
    public override CharacterGender Gender => CharacterGender.Neutral;  // or Male / Female
    public override int StartingHp => 60;

    // Point to your own pool classes
    public override CardPoolModel   CardPool   => ModelDb.CardPool<ArcanistCardPool>();
    public override RelicPoolModel  RelicPool  => ModelDb.RelicPool<ArcanistRelicPool>();
    public override PotionPoolModel PotionPool => ModelDb.PotionPool<ArcanistPotionPool>();

    // Starting deck — use ModelDb.Card<T>() (canonical, read-only)
    public override IEnumerable<CardModel> StartingDeck =>
    [
        ModelDb.Card<ArcaneStrike>(),
        ModelDb.Card<ArcaneStrike>(),
        ModelDb.Card<ArcaneStrike>(),
        ModelDb.Card<ArcaneDefend>(),
        ModelDb.Card<ArcaneDefend>(),
    ];

    // Starting relics — use ModelDb.Relic<T>() (canonical)
    public override IReadOnlyList<RelicModel> StartingRelics =>
        [ModelDb.Relic<ArcaneOrb>()];

    // Attack VFX paths used by architect enemies (copy from Ironclad if unsure)
    public override List<string> GetArchitectAttackVfx()
        => ["vfx/vfx_attack_slash", "vfx/vfx_attack_blunt", "vfx/vfx_heavy_blunt"];
}
```

### Pool classes (minimal implementations)
```csharp
// CardPool — name after character (e.g. Arcanist → ArcanistCardPool)
// Must set Title, IsColorless, CardFrameMaterialPath, ShaderColor, DeckEntryCardColor.
// CardFrameMaterialPath must be one of the built-in material names:
//   "card_frame_red", "card_frame_green", "card_frame_blue", "card_frame_orange",
//   "card_frame_pink", "card_frame_colorless", "card_frame_curse", "card_frame_quest"
// Use ShaderColor to recolor card_frame_red to any unique color (HSV shader).
public class ArcanistCardPool : CustomCardPoolModel
{
    public override string Title => "arcanist";
    public override bool IsColorless => false;
    public override string CardFrameMaterialPath => "card_frame_red";  // frame shape
    public override Color ShaderColor => new Color("7D3FC8FF");        // purple recolor
    public override Color DeckEntryCardColor => new Color("7D3FC8FF"); // deck list dot color
}

// RelicPool
public class ArcanistRelicPool : CustomRelicPoolModel { }

// PotionPool — needs to point to a parent pool (SharedPotionPool recommended)
public class ArcanistPotionPool : CustomPotionPoolModel
{
    public override PotionPoolModel? ParentPool => ModelDb.PotionPool<SharedPotionPool>();
}
```

### ModelDb pool accessors (add to sts2_api_reference if missing)
```csharp
ModelDb.CardPool<T>()    where T : CardPoolModel
ModelDb.RelicPool<T>()   where T : RelicPoolModel
ModelDb.PotionPool<T>()  where T : PotionPoolModel
```

### Character localization — requires a THIRD json file: characters.json
```json
// localization/eng/characters.json
{
  "S09_ARCANIST-ARCANIST.name": "Arcanist",
  "S09_ARCANIST-ARCANIST.description": "A wielder of arcane energies."
}
```
All three files needed: `cards.json`, `relics.json`, `characters.json` (eng + zhs).

### Registration
Characters register via `[Pool]` attribute (same mechanism as relics/cards) — no manual `ModelDb.Inject()` call needed if `PlaceholderCharacterModel` is used.
"""

_CUSTOM_CODE_DOCS = """
## Custom Code / Mechanics

For effects that don't fit card/relic/power:
- Typical approach: Harmony Prefix/Postfix patches + optional per-player state in a static dictionary keyed by Player instance.
- For buff counters with icons: use PowerModel (see Power section).

### Hook availability
Any class inheriting `AbstractModel` (RelicModel, CardModel, PowerModel, etc.) automatically
gets 60+ combat hooks via override. No Harmony patches needed for hooks that already exist.
Key Task hooks (full list in sts2_api_reference.md):
  AfterCardPlayed, AfterDamageReceived, AfterDamageGiven, AfterPlayerTurnStart,
  AfterTurnEnd, BeforeAttack, AfterAttack, AfterCombatEnd, AfterBlockGained, ...

### Key PileType values
None, Draw, Hand, Discard, Exhaust, Play, Deck

### Neow event injection (proven pattern — S00_DebugPicker / SFTestKit)
To add an option to the Neow opening event, Harmony-patch `Neow.GenerateInitialOptions`:

```csharp
using MegaCrit.Sts2.Core.Events;        // EventOption, IHoverTip
using MegaCrit.Sts2.Core.Models.Events; // Neow
using MegaCrit.Sts2.Core.Entities.Players;
using HarmonyLib;

[HarmonyPatch(typeof(Neow), "GenerateInitialOptions")]
public static class MyNeowPatch
{
    static void Postfix(Neow __instance, ref IReadOnlyList<EventOption> __result)
    {
        Player? player = __instance.Owner;
        if (player == null) return;

        var option = new EventOption(
            __instance,
            () => MyAction(player),          // async Task callback
            title: new MegaCrit.Sts2.Core.Localization.LocString("relics", "MY_KEY.title"),
            description: new MegaCrit.Sts2.Core.Localization.LocString("relics", "MY_KEY.description"),
            textKey: "my_key",
            hoverTips: Array.Empty<IHoverTip>()
        );
        var list = __result.ToList();
        list.Add(option);
        __result = list.AsReadOnly();
    }

    private static async Task MyAction(Player player)
    {
        // --- Card grid selection (shows ALL cards in scrollable grid, pick any number) ---
        var allCards = ModelDb.AllCards
            .Select(m => new CardCreationResult(player.RunState.CreateCard(m, player)))
            .ToList();
        var prefs = new CardSelectorPrefs(
            CardSelectorPrefs.UpgradeSelectionPrompt, 0, allCards.Count);
        var selected = (await CardSelectCmd.FromSimpleGridForRewards(
            new BlockingPlayerChoiceContext(), allCards, player, prefs)).ToList();
        foreach (var card in selected)
            CardCmd.PreviewCardPileAdd(await CardPileCmd.Add(card, PileType.Deck));

        // --- Relic selection (full scrollable list) ---
        var allRelics = ModelDb.AllRelics
            .Where(r => r.Rarity is not RelicRarity.Starter and not RelicRarity.None)
            .Select(r => r.ToMutable()).ToList();
        var picked = await RelicSelectCmd.FromChooseARelicScreen(player, allRelics);
        if (picked != null) player.AddRelicInternal(picked);
    }
}
```

**Localization for Neow option** (in `<ModName>/localization/eng/relics.json`):
```json
{"MY_KEY": {"title": "Option Label", "description": "What this option does."}}
```
Note: Neow options use the `"relics"` localization table regardless of content.
"""


# ── Public API ────────────────────────────────────────────────────────────────

# Maps asset_type → type-specific snippet
_TYPE_DOCS: dict[str, str] = {
    "card":            _CARD_DOCS,
    "card_fullscreen": _CARD_DOCS,
    "relic":           _RELIC_DOCS,
    "power":           _POWER_DOCS,
    "potion":          _POTION_DOCS,
    "character":       _CHARACTER_DOCS,
    "custom_code":     _CUSTOM_CODE_DOCS + "\n" + _POTION_DOCS + "\n" + _CHARACTER_DOCS,
}


def get_docs_for_type(asset_type: str) -> str:
    """
    Return the combined knowledge base for a specific asset type.
    Includes: common build/structure docs + type-specific API snippet.
    Does NOT include the full decompiled reference (too large for prompt injection).
    """
    type_specific = _TYPE_DOCS.get(asset_type, "")
    return _COMMON_DOCS + type_specific


def get_planner_api_hints() -> str:
    """
    Minimal API hints for the Planner LLM.
    Only names/pools/enums needed to write accurate implementation_notes.
    Full code examples are in the Code Agent prompt — keep this short.
    """
    return """
## STS2 API reference — use exact names in implementation_notes

### Card pools — pick by character/theme
| Pool | For | Notes |
|---|---|---|
| `IroncladCardPool` | Ironclad | strength, block, exhaust |
| `SilentCardPool` | Silent | poison, shivs, discard |
| `DefectCardPool` | Defect | orbs, focus |
| `RegentCardPool` | Regent | stances, mantras |
| `NecrobinderCardPool` | Necrobinder | undead, death |
| `ColorlessCardPool` | All characters | truly neutral cards only |
| `MyCharCardPool : CustomCardPoolModel` | New mod character | create if adding a new character |

### Base classes (use exact names)
- Card: `CustomCardModel` — ctor params: `baseCost, CardType, CardRarity, TargetType`
- Relic: `CustomRelicModel` — abstract prop: `RelicRarity Rarity`
- Power: `PowerModel` — abstract props: `PowerType Type`, `PowerStackType StackType`
- Potion: `CustomPotionModel` — override `OnUse(ctx, Creature?)`
- Character: `PlaceholderCharacterModel` — set `PlaceholderID => "ironclad"`

### Key enums
- `CardType`: Attack, Skill, Power, Status, Curse
- `CardRarity`: Common, Uncommon, Rare, Ancient
- `TargetType`: None, Self, AnyEnemy, AllEnemies, RandomEnemy
- `PowerType`: Buff, Debuff
- `PowerStackType`: None, Counter, Single
- `RelicRarity`: Starter, Common, Uncommon, Rare, Shop, Event
- `CardKeyword`: Exhaust, Ethereal, Innate, Retain, Sly, Eternal, Unplayable

### Built-in powers (do NOT redefine, use directly)
Debuffs: `PoisonPower`, `VulnerablePower`, `WeakPower`, `FrailPower`, `SlowPower`
Buffs: `StrengthPower`, `DexterityPower`, `ThornsPower`, `RegenPower`, `ArtifactPower`, `IntangiblePower`, `BarricadePower`, `VigorPower`, `RagePower`, `EnragePower`, `LethalityPower`, `FocusPower`, `EchoFormPower`

### Key rules for implementation_notes
- Card numbers MUST use `CanonicalVars` with `DamageVar`/`BlockVar`/`PowerVar<T>` — no hardcoded literals
- Localization uses `{Damage}`, `{PoisonPower}` placeholders matching var names
- `ExtraHoverTips` with `HoverTipFactory.FromPower<T>()` for power keyword tooltips on cards
- Relic hooks need `ShouldReceiveCombatHooks => true`
- Cards need `[Pool(typeof(SomeCardPool))]` attribute
- Card effect: `protected override async Task OnPlay(PlayerChoiceContext ctx, CardPlay cardPlay)`
- NEVER `new XxxModel()` — use `ModelDb.Card<T>()` / `.ToMutable()`
"""


# Legacy export: full docs for all types combined (kept for compatibility).
# Prefer get_docs_for_type(asset_type) in new code.
STS2_MOD_DOCS = (
    _COMMON_DOCS
    + _CARD_DOCS
    + _RELIC_DOCS
    + _POWER_DOCS
    + _CUSTOM_CODE_DOCS
)
